"""
SignalWatch API entrypoint.

Run locally:
    uvicorn main:app --reload --port 8000

OpenAPI docs are auto-generated by FastAPI at /docs and /redoc.
"""
from contextlib import asynccontextmanager

from dotenv import load_dotenv

# Must run before any of our own modules are imported: market_adapter and
# database.db both read environment variables (TWELVE_DATA_API_KEY,
# DATABASE_URL) at import time.
load_dotenv()

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from database.db import init_db
from routers import watchlist, market, changes, snapshot, insights


@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db()
    yield


app = FastAPI(
    title="SignalWatch API",
    description="Smart market watchlist: surfaces what meaningfully changed since you last looked.",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten to the deployed frontend origin in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    """
    Last-resort safety net: an unexpected error anywhere in the app
    returns a clean JSON 500 instead of leaking a stack trace or
    crashing the worker process.
    """
    return JSONResponse(
        status_code=500,
        content={"detail": "Something went wrong on our end. Please try again."},
    )


app.include_router(watchlist.router)
app.include_router(market.router)
app.include_router(changes.router)
app.include_router(snapshot.router)
app.include_router(insights.router)


@app.get("/", tags=["health"])
def health_check():
    return {"status": "ok", "service": "SignalWatch API"}
